#Rename
version: "3.7"
services:
  project-php:
    build:
      args:
        user: ${DOCKER_USER:-www}
        uid: ${DOCKER_UID:-1000}
      context: ./
      dockerfile: ./.docker/php/dockerfile
    container_name: ${APP_NAME}-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ~/.ssh:/home/${DOCKER_USER:-www}/.ssh
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - project-network

  project-nginx:
    build:
      context: ./
      dockerfile: ./.docker/nginx/nginx.dockerfile
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
     - '${DOCKER_HTTPS_PORT:-8000}:443'
     - '${DOCKER_HTTP_PORT:-8080}:80'
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - project-network
      

networks:
  project-network:
    name: ${APP_NAME}-network
    driver: bridge
